### ISSUE TITLE
Community ingestion

### ISSUE THREAD

**Issue by liambresnahan** [AdrianSimionov/obsidian-mindmap-nextgen#12]
Hi, nice to see that folks are working on this again, I was unaware but saw some merges referenced on obsidian-mind-map. 2 questions:

1. Do you plan to update the original repo to point to this new plugin?
2. Do you plan to ingest this to the Obsidian Community plugins?

**Comment by AdrianSimionov** [comment]
Answers:

1. I do not plan on updating the old repository.

**Comment by liambresnahan** [comment]
Understood on both. Thanks for the feedback.
