### ISSUE TITLE
Rendering seems slow and snappy

### ISSUE THREAD

**Issue by AdrianSimionov** [AdrianSimionov/obsidian-mindmap-nextgen#18]
Compared to markmap when used on the following link, updating the mindmap is very slow and does not have the same smooth nice effect.

https://markmap.js.org/repl

Expected behavior is to have a similar user experience by using the obsidian plugin.

**Comment by MasterTuto** [comment]
Pull request:

https://github.com/AdrianSimionov/obsidian-mindmap-nextgen/pull/22

**Comment by AdrianSimionov** [comment]
Tested, looks good now.
