### ISSUE TITLE
Set screenshot background color

### ISSUE THREAD

**Issue by MasterTuto** [AdrianSimionov/obsidian-mindmap-nextgen#23]
There are three possibilities:

1. Add a fixed setting so the user change the background color
2. Choose a math-based color based on the colors present in the picture (like, background would be in a range between black and white (#000 to #fff).
3. Make it transparent.

**Comment by AdrianSimionov** [comment]
Add two options:

1. Transparent PNG (can be default)
2. Allow user to set a BG color by specifying a HEX color value (this option will be used when user want the image to blend with the color there of the website where the mind-map is published)

I assumed here we are talking about the BG color when exporting the mind-map?

**Comment by MasterTuto** [comment]
Yeah, we're talking about exporting it. Using this option:

![image](https://user-images.githubusercontent.com/21978588/205471729-352c36e8-a262-4b36-848f-7872bd2648b5.png)

**Comment by AdrianSimionov** [comment]
This seems to work well already, and is actually taking a screenshot of the visible area.

**Comment by AdrianSimionov** [comment]
Can we change the DPI of the screenshot? I am using a monitor with high-dpi and while the mind-map looks very sharp on the screen when rendered, the screenshot PNG file is very fuzzy and obvious is not as sharp as it could be.

Maybe we can add an option to set the DPI? This way it would be future proof too, for 5K and upwards monitors.

**Comment by AdrianSimionov** [comment]
I have split this feature request into #43 and #44 

PNG export implemented by 55c7bc6f57f006e7a624f9db02edaa51e9a38384
