### ISSUE TITLE
Consistent inline-markmap CSS

### ISSUE THREAD

**Issue by AdrianSimionov** [AdrianSimionov/obsidian-mindmap-nextgen#45]
Expanding on the previously introduced inline-markmap, let use a similar CSS to display the inline markmap as other blocks of code are displayed.

<img width="722" alt="CleanShot 2022-12-13 at 15 57 47@2x" src="https://user-images.githubusercontent.com/6671693/207230662-6693241c-6ef5-49a2-b12b-2c8258319b72.png">

Previous screenshot shows how the code is in a different color, and with slightly rounded corners. Let's use a similar CSS approach for displaying inline mindmaps.

**Comment by MasterTuto** [comment]
Actually, to be fair the visual is as it should be. To a real example, one should compare with [mermaid](https://mermaid-js.github.io/mermaid/#/) which is a flowchart generator that works on obsidian and can be rendered as:

![image](https://user-images.githubusercontent.com/21978588/207355825-ae53070b-428b-4365-adc0-5905dc316d6e.png)

Which seems ok comparing to our output. That round and bordered are for code blocks.

I mean, if I understood it correctly.

**Comment by AdrianSimionov** [comment]
Well, there is a difference. With mermaid, the diagram is rendered and fixed, with no drag capability. With markmap, the diagram can be dragged. What happens is that without a border, the diagram suddenly disappears when outside of the DIV.

By adding a border, user would understand that the diagram disappears because is it restricted by the border.

Let's add a toggle button and front-matter settings to either display a different color DIV with border around the diagram, or leave it as it is, when the toggle is OFF.

By default, the toggle should be ON.

Please also add documentation text and a screenshot to the branch before we can merge.
